### ISSUE TITLE
1.20.1 Use of Game Version

### ISSUE THREAD

**Issue by 20030229** [OakPlatinum/clockin#2]
Add the 1.20.1 module to the server with many modules, and use the command to display the command that cannot be executed in the server.
If you use it in a new server, you cannot enter the server. The server console shows that the packet cannot be received.

**Comment by OakPlatinum** [comment]
_你用的是翻译器对吗？其实我会说中文 awa_

能够提供一下服务器端日志吗？谢谢！

**Comment by 20030229** [comment]
让我们说中文awa
![7dc72a45b4e52d7b393b208058cdc94c](https://github.com/user-attachments/assets/33a13e4e-0f76-420c-b13f-9ab6812a939b)
![ed7d239bb47eeb3fb330e0d8b7984c99](https://github.com/user-attachments/assets/9545a3aa-7a4f-4d63-a5fa-f4f7c705861d)
[2024-11-06-4.log.gz](https://github.com/user-attachments/files/17648415/2024-11-06-4.log.gz)
一个是控制台，一个是客户端

**Comment by OakPlatinum** [comment]
你确定你的sql服务器配置正确吗？你使用的是mysql还是sqlite？

**Comment by 20030229** [comment]
我用的是mysql，是没配置好这个问题吗，我再去查看一下。期间叨扰你了

**Comment by OakPlatinum** [comment]
没事的，大概可能是配置错误或者无法连接什么的，可以用相同的配置在GUI管理器或者终端测试下

**Comment by OakPlatinum** [comment]
这个其实也应该修一下，要不连接不上mysql服务器就无法加入了

**Comment by 20030229** [comment]
检查到了，是因为数据库没连接上。数据库写错了，结果属实难绷。有没有可以不适用数据库的办法

**Comment by OakPlatinum** [comment]
换成sqlite应该可以

**Comment by OakPlatinum** [comment]
换成sqlite应该可以，那个基本没有连接问题，我写mysql主要是因为我服务器要做多服互联什么的

**Comment by 20030229** [comment]
好的

**Comment by OakPlatinum** [comment]
那我就先把这个issue关了，至于其它的bug就再另开issue吧

**Comment by OakPlatinum** [comment]
@20030229 https://github.com/OakPlatinum/clockin/actions/runs/11706367949 bugfix版本，下载artifacts解压就行了
